### PR TITLE
Theme lookup

### PR DESCRIPTION
**Pull request by LadyLazorcorn**
Happy Hacktoberfest!
Ich find das Projekt echt toll und möchte es ein bisschen Design-technisch unterstützen ❤️

Bitte füge vor dem Merge unbedingt das Label "hacktoberfest-accepted" zu dem PR hinzu, sonst zählt es nicht für meine Hacktoberfest-Stats 😁 ✌️ 

Liebe Grüße aus Hamburg!
Susi

### CODE REVIEW

**Comment by xjcl** [comment]
Hi Susi,

thanks a lot for your effort and contributions. Sorry for getting back to you this late.

First of all: Is accepting/tagging the pull requests still relevant to you?

I think the Impressum/Datenschutz link was long overdue, and the change where I don't have to re-specify the theme color all the time is nice, I couldn't figure that one out. I personally liked the logo and add-marker icons better before.

There is some work to be done, the font is inconsistent in the main info bar and the ChipGroup still, plus the font feels "too high up", how did you get the font anyway? It's also very hard to review XML changes for me, I'm just not able to make sense of them (this is not your fault, more the fault of XML).

Greetings Jan

----

master:

Screenshot from 2020-11-14 20-30-28

pull request:

Screenshot from 2020-11-14 19-53-11

**Comment by LadyLazorcorn** [comment]
Hey Jan,

so good to hear from you ^^ Don't worry. This year's hacktoberfest had too
many boundaries anyway. Therefore you don't need to tag the PRs anymore. If
I can do something next year I will raise a hand before I start :D

To answer your question: I was checking which fonts (bitter) were used on
their website. You're right, this font is indeed a bit top-raised but I
thought it would be nice to stay consistent across their platforms (like
logo and colors). There is an option in Android Studio where you can
download and add fonts to your project. Then I set this as the default font
in your theme. Did you set a Style or TextAppearance for the info bar and
ChipGroup? That might be the reason for the occuring inconsistency.
Do you want me to check that?

Cheerio,
Susi


<https://susannbaumgart.com/contact/>

**Comment by xjcl** [comment]
Maybe I can wait to merge your changes until next Hacktoberfest, maybe it'll count then :D

Jokes aside, I'll try to merge your changes soon-ish. I don't really want to change the design of the app, but the Impressum and vector icons I'll definitely look at.

**Comment by xjcl** [comment]
I don't really understand what's going on here. There seems to be re-ordering of fields in the XML files (refactoring) but also some change of properties, I would prefer if these were cleanly separated so I can actually see what difference each change does. And as discussed, the official font does not look good as-implemented. Closing for now.

**Pull request closed without merging**
